apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-test
  labels:
    owned-by: "arpan"
spec:
  secretStoreRef:
    name: vault-backend-test
    kind: SecretStore
  target:
    name: my-secret
    creationPolicy: 'Owner'
    deletionPolicy: 'Merge'
    template:
      type: StringData
      data:
        username: '{{ .user }}'
        password: '{{ .pass }}'
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/devwebapp/config
      property: username
  - secretKey: pass
    remoteRef:
      key: secret/data/devwebapp/config
      property: password